# Generated by Django 3.0 on 2023-10-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_newsletteremail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='email_address_associate',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='email_address_password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='receiver_email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
